apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: my-guestbook:latest
        ## NOTE: The imagePullPolicy is set to IfNotPresent to avoid pulling the image from the registry
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "redis-service"  # Points to the Redis Service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
spec:
  type: NodePort
  selector:
    app: guestbook
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
